server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro_db?useUnicode=true&characterEncoding=utf8
    username: root
    password: 111111jun
mybatis:
    mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
    type-aliases-package: com.hujun.shirodemo02.pojo
    # 注意：对应实体类的路径
