server:
    port: 8080
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/wanlidadb?serverTimezone=UTC
        username: root
        password: 111111jun
        driver-class-name: com.mysql.jdbc.Driver
mybatis:
    mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
    type-aliases-package: com.example.entity
    # 注意：对应实体类的路径
